class GuiKeys:
    MenuKey = "-Menu-"
    DifficultyListBox = "-difficulty-"
    HeroCombo = "-hero-"
    TowerTypesListBox = "-chosen_tower_type-"
    ExistingTowersListBox = "-existing_towers-"
    XPositionInput = "-xpos-"
    YPositionInput = "-ypos-"
    NewTowerTypeInput = "-new_tower_type_input-"
    SaveTowerButton = '-save_tower_button-'
    KeyboardMouseButton = '-keyboard_mouse_button-'
    TopUpgradeButton = "-top_upgrade_button-"
    MiddleUpgradeButton = "-middle_upgrade_button-"
    BottomUpgradeButton = "-bottom_upgrade_button-"
    SellButton = "-sell_button-"
    TargetingButton = "-targeting_button-"
    SpecialTargetingButton = "-s_targeting_button-"
    ScriptBox = "-script_box-"
    DeleteFromScriptButton = "-delete-from-script"
    ModifyTowerButton = "-modify-tower-button"
    DuplicateTowerButton = "-duplicate-tower-button"
    DeleteTowerButton = "-delete-tower-button"
    MoveDownInScriptButton = "-move-down-in-script"
    MoveUpInScriptButton = "-move-up-in-script"

    CopyToClipboard = "-copy-to-clipboard-"
    PasteClipboard = "-paste-clipboard-"
